# Generated by Django 2.0.3 on 2018-03-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('attachment', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('has_hashtag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vgroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.Vgroup'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.Vgroup'),
        ),
    ]
