# Generated by Django 2.0.3 on 2018-04-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('vk_attachment_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('vk_timestamp', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('answered', models.BooleanField(default=False)),
                ('hashtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Hashtag')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
    ]
