# Generated by Django 2.0.3 on 2018-03-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='has_hashtag',
        ),
        migrations.AddField(
            model_name='history',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Hashtag'),
        ),
    ]
